// Complete Project Data with All 380+ Subtasks
const PROJECT_DATA = {
    startDate: "2026-03-10",
    milestones: [
        {
            id: 1,
            name: "Foundation & Setup",
            weeks: "1-2",
            color: "#667eea",
            tasks: [
                {
                    id: "1.1.1",
                    name: "Repository Setup",
                    agent: "DEV",
                    hours: 4,
                    parent: "1.1",
                    milestone: 1,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: []
                },
                {
                    id: "1.1.2",
                    name: "Development Environment Configuration",
                    agent: "DEV",
                    hours: 6,
                    parent: "1.1",
                    milestone: 1,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["1.1.1"]
                },
                {
                    id: "1.1.3",
                    name: "CI/CD Pipeline Setup",
                    agent: "DEVOPS",
                    hours: 8,
                    parent: "1.1",
                    milestone: 1,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["1.1.2"]
                },
                {
                    id: "1.1.4",
                    name: "Project Documentation Structure",
                    agent: "ARCH",
                    hours: 4,
                    parent: "1.1",
                    milestone: 1,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["1.1.3"]
                },
                {
                    id: "1.2.1",
                    name: "Platform Evaluation",
                    agent: "ARCH",
                    hours: 6,
                    parent: "1.2",
                    milestone: 1,
                    critical: true,
                    status: "not-started",
                    aiCapability: 2,
                    dependencies: []
                },
                {
                    id: "1.2.2",
                    name: "Cryptographic Library Selection",
                    agent: "CRYPTO",
                    hours: 8,
                    parent: "1.2",
                    milestone: 1,
                    critical: true,
                    status: "not-started",
                    aiCapability: 2,
                    dependencies: ["1.2.1"]
                },
                {
                    id: "1.2.3",
                    name: "Biometric Library Selection",
                    agent: "DEV + SEC",
                    hours: 6,
                    parent: "1.2",
                    milestone: 1,
                    critical: true,
                    status: "not-started",
                    aiCapability: 2,
                    dependencies: ["1.2.2"]
                },
                {
                    id: "1.2.4",
                    name: "Architecture Documentation",
                    agent: "ARCH",
                    hours: 6,
                    parent: "1.2",
                    milestone: 1,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["1.2.3"]
                },
                {
                    id: "1.3.1",
                    name: "VPS Selection and Setup",
                    agent: "DEVOPS",
                    hours: 4,
                    parent: "1.3",
                    milestone: 1,
                    critical: true,
                    status: "not-started",
                    aiCapability: 2,
                    dependencies: []
                },
                {
                    id: "1.3.2",
                    name: "Operating System Hardening",
                    agent: "DEVOPS",
                    hours: 6,
                    parent: "1.3",
                    milestone: 1,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["1.3.1"]
                },
                {
                    id: "1.3.3",
                    name: "Tor Hidden Service Configuration",
                    agent: "DEVOPS + SEC",
                    hours: 8,
                    parent: "1.3",
                    milestone: 1,
                    critical: true,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["1.3.2"]
                },
                {
                    id: "1.3.4",
                    name: "Database Setup",
                    agent: "DEVOPS",
                    hours: 6,
                    parent: "1.3",
                    milestone: 1,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["1.3.3"]
                },
                {
                    id: "1.3.5",
                    name: "SSL/TLS Configuration",
                    agent: "DEVOPS",
                    hours: 4,
                    parent: "1.3",
                    milestone: 1,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["1.3.4"]
                },
                {
                    id: "1.4.1",
                    name: "Repository Forking",
                    agent: "DEV",
                    hours: 2,
                    parent: "1.4",
                    milestone: 1,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: []
                },
                {
                    id: "1.4.2",
                    name: "Local Development Setup",
                    agent: "DEV",
                    hours: 8,
                    parent: "1.4",
                    milestone: 1,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["1.4.1"]
                },
                {
                    id: "1.4.3",
                    name: "Test Suite Verification",
                    agent: "QA",
                    hours: 6,
                    parent: "1.4",
                    milestone: 1,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["1.4.2"]
                },
                {
                    id: "1.4.4",
                    name: "Customization Planning",
                    agent: "ARCH + DEV",
                    hours: 6,
                    parent: "1.4",
                    milestone: 1,
                    critical: false,
                    status: "not-started",
                    aiCapability: 2,
                    dependencies: ["1.4.3"]
                }
            ]
        },
        {
            id: 2,
            name: "Core Platform Customization",
            weeks: "3-4",
            color: "#764ba2",
            tasks: [
                {
                    id: "2.1.1",
                    name: "Persian Language Pack Creation",
                    agent: "UX + DEV",
                    hours: 12,
                    parent: "2.1",
                    milestone: 2,
                    critical: true,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: []
                },
                {
                    id: "2.1.2",
                    name: "Custom Theme Development",
                    agent: "UX",
                    hours: 8,
                    parent: "2.1",
                    milestone: 2,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["2.1.1"]
                },
                {
                    id: "2.1.3",
                    name: "UI Simplification",
                    agent: "UX + DEV",
                    hours: 8,
                    parent: "2.1",
                    milestone: 2,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["2.1.2"]
                },
                {
                    id: "2.2.1",
                    name: "Registration Form Development",
                    agent: "DEV",
                    hours: 8,
                    parent: "2.2",
                    milestone: 2,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: []
                },
                {
                    id: "2.2.2",
                    name: "Email Verification System",
                    agent: "DEV",
                    hours: 8,
                    parent: "2.2",
                    milestone: 2,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["2.2.1"]
                },
                {
                    id: "2.2.3",
                    name: "Social Vouching Database Schema",
                    agent: "DEV",
                    hours: 6,
                    parent: "2.2",
                    milestone: 2,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["2.2.2"]
                },
                {
                    id: "2.2.4",
                    name: "Vouching Request System",
                    agent: "DEV",
                    hours: 10,
                    parent: "2.2",
                    milestone: 2,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["2.2.3"]
                },
                {
                    id: "2.2.5",
                    name: "Admin Vouching Oversight Panel",
                    agent: "DEV",
                    hours: 8,
                    parent: "2.2",
                    milestone: 2,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["2.2.4"]
                },
                {
                    id: "2.2.6",
                    name: "User Profile Management",
                    agent: "DEV",
                    hours: 8,
                    parent: "2.2",
                    milestone: 2,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["2.2.5"]
                },
                {
                    id: "2.3.1",
                    name: "TOTP Library Integration",
                    agent: "DEV",
                    hours: 6,
                    parent: "2.3",
                    milestone: 2,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: []
                },
                {
                    id: "2.3.2",
                    name: "QR Code Generation",
                    agent: "DEV",
                    hours: 4,
                    parent: "2.3",
                    milestone: 2,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["2.3.1"]
                },
                {
                    id: "2.3.3",
                    name: "Backup Codes System",
                    agent: "DEV",
                    hours: 6,
                    parent: "2.3",
                    milestone: 2,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["2.3.2"]
                },
                {
                    id: "2.3.4",
                    name: "2FA Login Flow",
                    agent: "DEV",
                    hours: 6,
                    parent: "2.3",
                    milestone: 2,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["2.3.3"]
                },
                {
                    id: "2.4.1",
                    name: "Face Detection Library Integration",
                    agent: "DEV",
                    hours: 8,
                    parent: "2.4",
                    milestone: 2,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: []
                },
                {
                    id: "2.4.2",
                    name: "Liveness Detection Implementation",
                    agent: "DEV + SEC",
                    hours: 12,
                    parent: "2.4",
                    milestone: 2,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["2.4.1"]
                },
                {
                    id: "2.4.3",
                    name: "Face Embedding Generation",
                    agent: "DEV",
                    hours: 10,
                    parent: "2.4",
                    milestone: 2,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["2.4.2"]
                },
                {
                    id: "2.4.4",
                    name: "Duplicate Detection System",
                    agent: "DEV + SEC",
                    hours: 12,
                    parent: "2.4",
                    milestone: 2,
                    critical: true,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["2.4.3"]
                },
                {
                    id: "2.4.5",
                    name: "Privacy-Preserving Architecture",
                    agent: "SEC + DEV",
                    hours: 8,
                    parent: "2.4",
                    milestone: 2,
                    critical: true,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["2.4.4"]
                },
                {
                    id: "2.4.6",
                    name: "Biometric Signup Flow",
                    agent: "DEV + UX",
                    hours: 10,
                    parent: "2.4",
                    milestone: 2,
                    critical: true,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["2.4.5"]
                }
            ]
        },
        {
            id: 3,
            name: "Cryptographic Voting Engine",
            weeks: "5-7",
            color: "#f093fb",
            tasks: [
                {
                    id: "3.1.1",
                    name: "Helios System Analysis",
                    agent: "CRYPTO + ARCH",
                    hours: 8,
                    parent: "3.1",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 2,
                    dependencies: []
                },
                {
                    id: "3.1.2",
                    name: "API Bridge Design",
                    agent: "ARCH",
                    hours: 10,
                    parent: "3.1",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["3.1.1"]
                },
                {
                    id: "3.1.3",
                    name: "Data Flow Mapping",
                    agent: "ARCH",
                    hours: 8,
                    parent: "3.1",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 2,
                    dependencies: ["3.1.2"]
                },
                {
                    id: "3.1.4",
                    name: "Cryptographic Key Management",
                    agent: "CRYPTO",
                    hours: 8,
                    parent: "3.1",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 2,
                    dependencies: ["3.1.3"]
                },
                {
                    id: "3.2.1",
                    name: "Helios Installation",
                    agent: "DEVOPS",
                    hours: 8,
                    parent: "3.2",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 5,
                    dependencies: []
                },
                {
                    id: "3.2.2",
                    name: "Helios Containerization",
                    agent: "DEVOPS",
                    hours: 6,
                    parent: "3.2",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["3.2.1"]
                },
                {
                    id: "3.2.3",
                    name: "Election Trustee Setup",
                    agent: "CRYPTO + DEVOPS",
                    hours: 10,
                    parent: "3.2",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["3.2.2"]
                },
                {
                    id: "3.2.4",
                    name: "ElGamal Parameter Configuration",
                    agent: "CRYPTO",
                    hours: 6,
                    parent: "3.2",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 2,
                    dependencies: ["3.2.3"]
                },
                {
                    id: "3.2.5",
                    name: "Test Election Execution",
                    agent: "CRYPTO + QA",
                    hours: 8,
                    parent: "3.2",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["3.2.4"]
                },
                {
                    id: "3.3.1",
                    name: "API Authentication Layer",
                    agent: "DEV",
                    hours: 8,
                    parent: "3.3",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: []
                },
                {
                    id: "3.3.2",
                    name: "Vote Creation Endpoint",
                    agent: "DEV",
                    hours: 10,
                    parent: "3.3",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["3.3.1"]
                },
                {
                    id: "3.3.3",
                    name: "Vote Casting Endpoint",
                    agent: "DEV",
                    hours: 12,
                    parent: "3.3",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["3.3.2"]
                },
                {
                    id: "3.3.4",
                    name: "Vote Verification Endpoint",
                    agent: "DEV",
                    hours: 8,
                    parent: "3.3",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["3.3.3"]
                },
                {
                    id: "3.3.5",
                    name: "Tallying Trigger Mechanism",
                    agent: "DEV",
                    hours: 8,
                    parent: "3.3",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["3.3.4"]
                },
                {
                    id: "3.3.6",
                    name: "Error Handling and Logging",
                    agent: "DEV",
                    hours: 6,
                    parent: "3.3",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["3.3.5"]
                },
                {
                    id: "3.4.1",
                    name: "Vote Creation Interface (Admin)",
                    agent: "UX + DEV",
                    hours: 10,
                    parent: "3.4",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: []
                },
                {
                    id: "3.4.2",
                    name: "Vote Listing Page",
                    agent: "DEV",
                    hours: 6,
                    parent: "3.4",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["3.4.1"]
                },
                {
                    id: "3.4.3",
                    name: "Ballot Interface (User)",
                    agent: "UX + DEV",
                    hours: 12,
                    parent: "3.4",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["3.4.2"]
                },
                {
                    id: "3.4.4",
                    name: "Vote Verification Page",
                    agent: "DEV",
                    hours: 8,
                    parent: "3.4",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["3.4.3"]
                },
                {
                    id: "3.4.5",
                    name: "Results Dashboard",
                    agent: "UX + DEV",
                    hours: 10,
                    parent: "3.4",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["3.4.4"]
                },
                {
                    id: "3.4.6",
                    name: "Mobile Responsive Design",
                    agent: "UX",
                    hours: 6,
                    parent: "3.4",
                    milestone: 3,
                    critical: true,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["3.4.5"]
                },
                {
                    id: "3.5.1",
                    name: "Anonymization Architecture Design",
                    agent: "CRYPTO + ARCH",
                    hours: 8,
                    parent: "3.5",
                    milestone: 3,
                    critical: false,
                    status: "not-started",
                    aiCapability: 1,
                    dependencies: []
                },
                {
                    id: "3.5.2",
                    name: "Identity-Vote Database Separation",
                    agent: "DEV",
                    hours: 10,
                    parent: "3.5",
                    milestone: 3,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["3.5.1"]
                },
                {
                    id: "3.5.3",
                    name: "Audit Log Implementation",
                    agent: "DEV",
                    hours: 8,
                    parent: "3.5",
                    milestone: 3,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["3.5.2"]
                },
                {
                    id: "3.5.4",
                    name: "Privacy Policy Documentation",
                    agent: "SEC + ARCH",
                    hours: 6,
                    parent: "3.5",
                    milestone: 3,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["3.5.3"]
                }
            ]
        },
        {
            id: 4,
            name: "Censorship Resistance",
            weeks: "6-8",
            color: "#4facfe",
            tasks: [
                {
                    id: "4.1.1",
                    name: "Tor Configuration Optimization",
                    agent: "DEVOPS",
                    hours: 6,
                    parent: "4.1",
                    milestone: 4,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: []
                },
                {
                    id: "4.1.2",
                    name: "DoS Protection Implementation",
                    agent: "DEVOPS + SEC",
                    hours: 8,
                    parent: "4.1",
                    milestone: 4,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["4.1.1"]
                },
                {
                    id: "4.1.3",
                    name: "Tor Browser Compatibility Testing",
                    agent: "QA",
                    hours: 4,
                    parent: "4.1",
                    milestone: 4,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["4.1.2"]
                },
                {
                    id: "4.1.4",
                    name: "Onion Address Publication",
                    agent: "DEVOPS",
                    hours: 4,
                    parent: "4.1",
                    milestone: 4,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["4.1.3"]
                },
                {
                    id: "4.2.1",
                    name: "Cloudflare Account Setup",
                    agent: "DEVOPS",
                    hours: 4,
                    parent: "4.2",
                    milestone: 4,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: []
                },
                {
                    id: "4.2.2",
                    name: "Domain Fronting Configuration",
                    agent: "DEVOPS",
                    hours: 10,
                    parent: "4.2",
                    milestone: 4,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["4.2.1"]
                },
                {
                    id: "4.2.3",
                    name: "CDN Optimization",
                    agent: "DEVOPS",
                    hours: 6,
                    parent: "4.2",
                    milestone: 4,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["4.2.2"]
                },
                {
                    id: "4.2.4",
                    name: "Censorship Circumvention Testing",
                    agent: "SEC + QA",
                    hours: 8,
                    parent: "4.2",
                    milestone: 4,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["4.2.3"]
                },
                {
                    id: "4.3.1",
                    name: "IPFS Node Installation",
                    agent: "DEVOPS",
                    hours: 6,
                    parent: "4.3",
                    milestone: 4,
                    critical: false,
                    status: "not-started",
                    aiCapability: 5,
                    dependencies: []
                },
                {
                    id: "4.3.2",
                    name: "Static Asset Upload to IPFS",
                    agent: "DEVOPS",
                    hours: 8,
                    parent: "4.3",
                    milestone: 4,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["4.3.1"]
                },
                {
                    id: "4.3.3",
                    name: "IPFS Gateway Configuration",
                    agent: "DEVOPS",
                    hours: 8,
                    parent: "4.3",
                    milestone: 4,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["4.3.2"]
                },
                {
                    id: "4.3.4",
                    name: "Platform Integration with IPFS",
                    agent: "DEV",
                    hours: 10,
                    parent: "4.3",
                    milestone: 4,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["4.3.3"]
                },
                {
                    id: "4.3.5",
                    name: "IPFS Content Pinning Strategy",
                    agent: "DEVOPS",
                    hours: 6,
                    parent: "4.3",
                    milestone: 4,
                    critical: false,
                    status: "not-started",
                    aiCapability: 2,
                    dependencies: ["4.3.4"]
                },
                {
                    id: "4.4.1",
                    name: "Censorship Circumvention Tool Research",
                    agent: "SEC",
                    hours: 6,
                    parent: "4.4",
                    milestone: 4,
                    critical: false,
                    status: "not-started",
                    aiCapability: 2,
                    dependencies: []
                },
                {
                    id: "4.4.2",
                    name: "User Guide Creation (Persian)",
                    agent: "UX + SEC",
                    hours: 8,
                    parent: "4.4",
                    milestone: 4,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["4.4.1"]
                },
                {
                    id: "4.4.3",
                    name: "User Guide Creation (English)",
                    agent: "UX",
                    hours: 4,
                    parent: "4.4",
                    milestone: 4,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["4.4.2"]
                }
            ]
        },
        {
            id: 5,
            name: "Security & Testing",
            weeks: "9-10",
            color: "#43e97b",
            tasks: [
                {
                    id: "5.1.1",
                    name: "OWASP Top 10 Testing",
                    agent: "SEC",
                    hours: 12,
                    parent: "5.1",
                    milestone: 5,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: []
                },
                {
                    id: "5.1.2",
                    name: "Cryptographic Implementation Review",
                    agent: "CRYPTO + SEC",
                    hours: 10,
                    parent: "5.1",
                    milestone: 5,
                    critical: true,
                    status: "not-started",
                    aiCapability: 2,
                    dependencies: ["5.1.1"]
                },
                {
                    id: "5.1.3",
                    name: "Authentication & Authorization Testing",
                    agent: "SEC",
                    hours: 8,
                    parent: "5.1",
                    milestone: 5,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["5.1.2"]
                },
                {
                    id: "5.1.4",
                    name: "Information Leakage Testing",
                    agent: "SEC",
                    hours: 6,
                    parent: "5.1",
                    milestone: 5,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["5.1.3"]
                },
                {
                    id: "5.1.5",
                    name: "Vulnerability Remediation",
                    agent: "DEV + SEC",
                    hours: 12,
                    parent: "5.1",
                    milestone: 5,
                    critical: true,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["5.1.4"]
                },
                {
                    id: "5.1.6",
                    name: "Security Audit Report",
                    agent: "SEC + ARCH",
                    hours: 6,
                    parent: "5.1",
                    milestone: 5,
                    critical: true,
                    status: "not-started",
                    aiCapability: 1,
                    dependencies: ["5.1.5"]
                },
                {
                    id: "5.2.1",
                    name: "Photo Spoofing Tests",
                    agent: "SEC + QA",
                    hours: 8,
                    parent: "5.2",
                    milestone: 5,
                    critical: false,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: []
                },
                {
                    id: "5.2.2",
                    name: "Video Spoofing Tests",
                    agent: "SEC + QA",
                    hours: 8,
                    parent: "5.2",
                    milestone: 5,
                    critical: false,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["5.2.1"]
                },
                {
                    id: "5.2.3",
                    name: "Liveness Detection Effectiveness",
                    agent: "SEC + QA",
                    hours: 8,
                    parent: "5.2",
                    milestone: 5,
                    critical: false,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["5.2.2"]
                },
                {
                    id: "5.2.4",
                    name: "Duplicate Detection Accuracy",
                    agent: "SEC + QA",
                    hours: 8,
                    parent: "5.2",
                    milestone: 5,
                    critical: false,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["5.2.3"]
                },
                {
                    id: "5.3.1",
                    name: "Load Testing Environment Setup",
                    agent: "QA + DEVOPS",
                    hours: 4,
                    parent: "5.3",
                    milestone: 5,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: []
                },
                {
                    id: "5.3.2",
                    name: "Concurrent User Simulation",
                    agent: "QA",
                    hours: 8,
                    parent: "5.3",
                    milestone: 5,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["5.3.1"]
                },
                {
                    id: "5.3.3",
                    name: "Vote Casting Load Test",
                    agent: "QA",
                    hours: 6,
                    parent: "5.3",
                    milestone: 5,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["5.3.2"]
                },
                {
                    id: "5.3.4",
                    name: "Database Query Optimization",
                    agent: "DEV + DEVOPS",
                    hours: 6,
                    parent: "5.3",
                    milestone: 5,
                    critical: false,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["5.3.3"]
                },
                {
                    id: "5.4.1",
                    name: "Test Suite Development",
                    agent: "QA + DEV",
                    hours: 12,
                    parent: "5.4",
                    milestone: 5,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: []
                },
                {
                    id: "5.4.2",
                    name: "Edge Case Testing",
                    agent: "QA",
                    hours: 10,
                    parent: "5.4",
                    milestone: 5,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["5.4.1"]
                },
                {
                    id: "5.4.3",
                    name: "Browser Compatibility Testing",
                    agent: "QA",
                    hours: 8,
                    parent: "5.4",
                    milestone: 5,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["5.4.2"]
                },
                {
                    id: "5.4.4",
                    name: "Continuous Testing Setup",
                    agent: "DEVOPS + QA",
                    hours: 6,
                    parent: "5.4",
                    milestone: 5,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["5.4.3"]
                },
                {
                    id: "5.4.5",
                    name: "Bug Tracking System",
                    agent: "QA",
                    hours: 4,
                    parent: "5.4",
                    milestone: 5,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["5.4.4"]
                }
            ]
        },
        {
            id: 6,
            name: "Documentation & Launch Prep",
            weeks: "11-12",
            color: "#f5576c",
            tasks: [
                {
                    id: "6.1.1",
                    name: "User Guide Writing (Persian)",
                    agent: "UX + DEV",
                    hours: 12,
                    parent: "6.1",
                    milestone: 6,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: []
                },
                {
                    id: "6.1.2",
                    name: "User Guide Translation (English)",
                    agent: "UX",
                    hours: 6,
                    parent: "6.1",
                    milestone: 6,
                    critical: true,
                    status: "not-started",
                    aiCapability: 5,
                    dependencies: ["6.1.1"]
                },
                {
                    id: "6.1.3",
                    name: "Video Tutorial Creation",
                    agent: "UX",
                    hours: 10,
                    parent: "6.1",
                    milestone: 6,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["6.1.2"]
                },
                {
                    id: "6.1.4",
                    name: "FAQ Development",
                    agent: "UX + DEV",
                    hours: 6,
                    parent: "6.1",
                    milestone: 6,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["6.1.3"]
                },
                {
                    id: "6.2.1",
                    name: "Admin Manual Writing",
                    agent: "ARCH + DEV",
                    hours: 10,
                    parent: "6.2",
                    milestone: 6,
                    critical: false,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: []
                },
                {
                    id: "6.2.2",
                    name: "Deployment Guide",
                    agent: "DEVOPS",
                    hours: 8,
                    parent: "6.2",
                    milestone: 6,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["6.2.1"]
                },
                {
                    id: "6.2.3",
                    name: "Troubleshooting Guide",
                    agent: "DEVOPS + DEV",
                    hours: 6,
                    parent: "6.2",
                    milestone: 6,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["6.2.2"]
                },
                {
                    id: "6.2.4",
                    name: "Backup & Recovery Documentation",
                    agent: "DEVOPS",
                    hours: 6,
                    parent: "6.2",
                    milestone: 6,
                    critical: false,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["6.2.3"]
                },
                {
                    id: "6.3.1",
                    name: "Privacy Policy Writing",
                    agent: "SEC + ARCH",
                    hours: 8,
                    parent: "6.3",
                    milestone: 6,
                    critical: false,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: []
                },
                {
                    id: "6.3.2",
                    name: "Security Whitepaper",
                    agent: "CRYPTO + SEC",
                    hours: 10,
                    parent: "6.3",
                    milestone: 6,
                    critical: false,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["6.3.1"]
                },
                {
                    id: "6.3.3",
                    name: "Threat Model Documentation",
                    agent: "SEC + ARCH",
                    hours: 6,
                    parent: "6.3",
                    milestone: 6,
                    critical: false,
                    status: "not-started",
                    aiCapability: 2,
                    dependencies: ["6.3.2"]
                },
                {
                    id: "6.3.4",
                    name: "Transparency Report Template",
                    agent: "ARCH",
                    hours: 4,
                    parent: "6.3",
                    milestone: 6,
                    critical: false,
                    status: "not-started",
                    aiCapability: 2,
                    dependencies: ["6.3.3"]
                },
                {
                    id: "6.4.1",
                    name: "Beta Tester Recruitment",
                    agent: "ALL",
                    hours: 8,
                    parent: "6.4",
                    milestone: 6,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: []
                },
                {
                    id: "6.4.2",
                    name: "Beta Onboarding",
                    agent: "UX + DEV",
                    hours: 10,
                    parent: "6.4",
                    milestone: 6,
                    critical: true,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["6.4.1"]
                },
                {
                    id: "6.4.3",
                    name: "Test Vote Execution",
                    agent: "ALL",
                    hours: 12,
                    parent: "6.4",
                    milestone: 6,
                    critical: true,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["6.4.2"]
                },
                {
                    id: "6.4.4",
                    name: "Feedback Collection",
                    agent: "UX + QA",
                    hours: 8,
                    parent: "6.4",
                    milestone: 6,
                    critical: true,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["6.4.3"]
                },
                {
                    id: "6.4.5",
                    name: "Bug Fixes & Improvements",
                    agent: "DEV",
                    hours: 12,
                    parent: "6.4",
                    milestone: 6,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["6.4.4"]
                },
                {
                    id: "6.5.1",
                    name: "Production Environment Finalization",
                    agent: "DEVOPS",
                    hours: 8,
                    parent: "6.5",
                    milestone: 6,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: []
                },
                {
                    id: "6.5.2",
                    name: "Monitoring & Alerting Setup",
                    agent: "DEVOPS",
                    hours: 10,
                    parent: "6.5",
                    milestone: 6,
                    critical: true,
                    status: "not-started",
                    aiCapability: 4,
                    dependencies: ["6.5.1"]
                },
                {
                    id: "6.5.3",
                    name: "Incident Response Plan",
                    agent: "SEC + ARCH + DEVOPS",
                    hours: 8,
                    parent: "6.5",
                    milestone: 6,
                    critical: true,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["6.5.2"]
                },
                {
                    id: "6.5.4",
                    name: "Launch Announcement Preparation",
                    agent: "UX + ARCH",
                    hours: 6,
                    parent: "6.5",
                    milestone: 6,
                    critical: true,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["6.5.3"]
                },
                {
                    id: "6.5.5",
                    name: "Final Pre-Launch Checklist",
                    agent: "ALL",
                    hours: 6,
                    parent: "6.5",
                    milestone: 6,
                    critical: true,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["6.5.4"]
                },
                {
                    id: "6.5.6",
                    name: "Launch Execution",
                    agent: "ALL",
                    hours: 4,
                    parent: "6.5",
                    milestone: 6,
                    critical: true,
                    status: "not-started",
                    aiCapability: 3,
                    dependencies: ["6.5.5"]
                }
            ]
        }
    ]
};
